config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  resources :pages , only: [:index]
  resources :products, only: [:index]
  get 'products/recommended', to: 'products#recommended', as:'recommended'


  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administration.rb
class Administration < ApplicationRecord
  has_one_attached :photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :super_category
  has_many :products
  has_many :headers, through: :products
  has_many :countries, through: :products
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :products
  has_many :headers, through: :products
  has_one_attached :photo
end

app/models/header.rb
class Header < ApplicationRecord
  has_many :products
  has_many :countries, through: :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    self.quantity * self.product.price
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :country, optional: true
  belongs_to :winery, optional: true
  belongs_to :header, optional: true
  has_one_attached :photo
  monetize :price_cents
  has_many :line_items




  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :description, :year],
    associated_against: {
      category: [ :name],
      country: [ :name],
      winery: [ :name],
      header: [ :name],

    },
    using: {
      tsearch: { prefix: true }
    }


end

app/models/super_category.rb
class SuperCategory < ApplicationRecord
    has_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/winery.rb
class Winery < ApplicationRecord
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :current_cart

  private
    def current_cart
      if session[:cart_id]
        cart = Cart.find_by(:id => session[:cart_id])
        if cart.present?
          @current_cart = cart
        else
          session[:cart_id] = nil
        end
      end

      if session[:cart_id] == nil
        @current_cart = Cart.create
        session[:cart_id] = @current_cart.id
      end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :destroy]
  def show
    @super_categories= SuperCategory.includes([:categories])
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create, :destroy, :add_quantity, :reduce_quantity]
  def create
    chosen_product = Product.find(params[:product_id])
    current_cart = @current_cart


    if current_cart.products.include?(chosen_product)
      @line_item = current_cart.line_items.find_by(product_id: chosen_product)
      @line_item.quantity += 1
    else
      @line_item = LineItem.new
      @line_item.cart = current_cart
      @line_item.product = chosen_product
    end
    @line_item.save
    redirect_to cart_path(current_cart)
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to cart_path(@current_cart)
  end


  def add_quantity
    @line_item = LineItem.find(params[:id])
    @line_item.quantity += 1
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    @line_item = LineItem.find(params[:id])
    if @line_item.quantity > 1
      @line_item.quantity -= 1
    end
    @line_item.save
    redirect_to cart_path(@current_cart)
  end



private
  def line_item_params
    params.require(:line_item).permit(:quantity,:product_id, :cart_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index]

  def home
    @super_categories = SuperCategory.all
    @administration = Administration.first

  end

  def index
    @super_categories = SuperCategory.includes(:categories)
    @product = Product.new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :recommended]


  def index
    @cart = @current_cart
    @super_categories= SuperCategory.includes([:categories])
    @line_items = LineItem.where('cart_id = ?', @cart.id)

    if search_params[:super_category].present?
      @category_overview = Category.joins(:super_category).where("super_categories.name = ?", search_params[:super_category])

    elsif search_params[:query].present?
      @search = 1 #until pg:multisearchable inculded
      @products = Product.global_search(search_params[:query])
      @query = search_params[:query]

    else
      @category = Category.find_by(name: search_params[:category])
    end
  end

  def recommended
    @super_categories= SuperCategory.includes([:categories])
    @recommended_products = Product.where(premium: true)
    @recommended_categories = Category.joins(:products).where("products.premium = ?", true)

  end


private
  def search_params
    params.require(:products).permit(:category, :query, :super_category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<div class="con">
  <div class="side"></div>
  <div class="middle overview "><%= render 'shared/navbar', super_categories: @super_categories %>
    <div class="overview-headline">
      <h1>Warenkorb</h1>
    </div>

    <div class="overview-product">
      <ul>
        <% @cart.line_items.each do |line_item| %>
          <li><%= line_item.product.name %>/ Preis: <%= humanized_money_with_symbol(line_item.product.price) %>/ Anzahl: <%= line_item.quantity %>/ Preis gesamt: <%= humanized_money_with_symbol(line_item.total_price) %>
          <ul>
            <li>
              <%= link_to "Plus", line_item_add_path(:id => line_item), method: :post %>
              <%= link_to "Minus", line_item_reduce_path(:id => line_item), method: :post %>
            </li>
            <li>
              <%= link_to "Löschen", line_item_path(line_item), method: :delete %>
            </li>
          </ul>
        <% end %>
      </ul>
      <h3>Gesamt: <%= humanized_money_with_symbol(@cart.sub_total) %></h3>
      <%= link_to "Warenkorb leeren", cart_path(@current_cart),method: :delete, data: {confirm: "Sind Sie sicher?"} %>
    </div>



  </div>
  <div class="side"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="con">
  <div class="side"></div>
  <div class="home middle ">
    <div class="home-header">
      <div class="home-header-image"> <h1><%=image_tag 'barthel.png' %></h1></div>
      <div class="home-header-name">
        <h1><%=@administration.name.upcase%></h1>
        <h2><%=@administration.subtitle.upcase%></h2>
      </div>
      <div class="home-header-empty"></div>
    </div>
    <div class="home-top">
      <h3><%=@administration.street_name%></h3>
      <h3> <%=@administration.opening_time%></h3>
      <h3>Tel:<%=@administration.telephone_number%> | <%=@administration.email%></h3>
    </div>
    <div class="home-main">
      <div class="home-main-super_categories">
        <% @super_categories.each do |super_category| %>
          <h3><%= button_to "#{super_category.name.upcase}", products_path, method: :get, params: {products: {super_category: super_category.name}}, class: "home-main-super_categories-item" %></h3>
        <% end %>
      </div>
      <div class="home-main-image">
        <% if @administration.photo.attached?  %>
          <%= cl_image_tag @administration.photo.key, height: 1000, width: 1000, crop: :fill %>
        <% end %>
      </div>
    </div>
    <div class="home-link">
      <%if @administration.infobox.present? %>
       <h3><%= @administration.infobox%></h3>
      <% end %>
       <%= link_to pages_path do%>
       <h2>ONLINE BESTELLEN</h2>
       <% end %>
    </div>
    <div class="home-footer">
      <div class="home-footer-bottom">
        <h3>KONTAKT</h3>
        <h3>IMPRESSUM</h3>
        <h3>SERVICE & KONDITIONEN</h3>
      </div>
    </div>
  </div>
  <div class="side"></div>
</div>

app/views/pages/index.html.erb
<div class="con">
  <div class="side"></div>
  <div class="middle overview "><%= render 'shared/navbar', super_categories: @super_categories %>
    <div class="overview-headline">
      <h1>UNSER SORTIMENT</h1>
    </div>

    <div class="overview-search">
      <%= simple_form_for :products, url: products_path, method: "GET" do |f| %>
        <%= f.input :query, input_html: {value: ""} %>
        <%= f.submit "SUCHEN", class: "btn btn-primary" , id:'btn-search'%>
      <% end %>
    </div>

    <div class="overview-product">
      <% @super_categories.each do |super_category| %>

        <div class="overview-product-super_category big">
          <h1 class= "overview-product-super_category-item"><%=super_category.name.upcase %></h1>
          <div class="overview-product-category-static">
          <% super_category.categories.each do |category| %>
            <% if super_category.name == 'Barthel Spezial' %>
              <h3><%= button_to "EMPFEHLUNGEN", recommended_path , method: :get, class: "overview-product-category-item"%></h3>
            <% end %>
            <h3><%= button_to "#{category.name.upcase}", products_path, method: :get, params: {products: {category: category.name}}, class: "overview-product-category-item" %></h3>
            <% end %>
          </div>
        </div>

        <div class="overview-product-super_category small">
          <h1 class= "overview-product-super_category-item"><%= button_to "#{super_category.name.upcase}", products_path, method: :get, params: {products: {super_category: super_category.name}}, class: "overview-product-super_category-item" %></h1>
        </div>

      <% end %>
    </div>



  </div>
  <div class="side"></div>
</div>

app/views/products/index.html.erb
<div class="con">
  <div class="side"></div>
  <div class="middle">
    <%= render 'shared/navbar', super_categories: @super_categories %>

    <% if @category_overview.present? %>
      <div class="category_overview">
        <% @category_overview.each do |category| %>
          <% if category.super_category.name == 'Barthel Spezial' %>
           <%= button_to recommended_path, method: :get, class: "category-overview-item" do%>
             <h2>EMPFEHLUNGEN</h2>
           <% end %>
          <% end %>
          <%= button_to products_path, method: :get, params: {products: {category: category.name}}, class: "category-overview-item" do%>
            <h2><%= category.name.upcase%></h2>
          <% end %>
        <% end %>
      </div>



    <% elsif @search.present? %>
      <% if @products.present? %>
        <div class="category-name">
          <h3> Unsere Ergebnisse zu  <i><%=@query%></i></h3>
        </div>
         <%@products.each do |product| %>
          <%= render 'shared/product-card', product: product %>
         <% end %>
      <% else %>
        <div class="category-name">
          <h3> Leider konnten wir zu Ihrer Suche keine Produkte in unserem Sortiment finden</h3>
        </div>
      <% end %>
    <% else %>
      <% if @category.present? && @category.products.present? %>
        <div class="category-name">
          <h2 ><%= @category.name.upcase %></h2>
        </div>

        <% if @category.super_category.name == 'Weine' %>
          <div class="country-selection">
            <%@category.countries.uniq.each do |country| %>
              <div class="country-selection-card">
                <% if country.photo.attached?  %>
                  <%= cl_image_tag country.photo.key, height: 60, width: 60, crop: :fill %>
                <% else %>
                  <%= image_tag 'globe.svg' %>
                <% end %>
                <h4 class="country-selection-button" ><%= country.name.upcase %></h4>
              </div>

            <% end %>
          </div>

          <%@category.countries.uniq.each do |country| %>
            <div class="country-wines">
              <h3 class="country-name"><%= country.name.upcase %></h3>
              <% @category.headers.uniq.each do |header| %>
                <% if  header.countries.include?(country) %>
                  <h3 class="header-name"><%= header.name.upcase %></h3>
                <% end %>
                <%@category.products.each do |product| %>
                    <% if product.country == country && product.header == header%>
                      <%= render 'shared/product-card', product: product %>
                    <%end %>
                <% end %>
              <% end %>
            </div>

          <% end %>

        <% else %>
          <%@category.headers.uniq.each do |header| %>
            <h3 class="header-name"><%= header.name.upcase %></h3>
            <%header.products.each do |product| %>
              <%= render 'shared/product-card', product: product %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

  </div>
  <div class="side"></div>
</div>

app/views/products/recommended.html.erb
<div class="con">
  <div class="side"></div>
  <div class="middle">
    <%= render 'shared/navbar', super_categories: @super_categories %>
    <div class="category-name">
      <h2>EMPFEHLUNGEN</h2>
    </div>

    <% @recommended_categories.uniq.each do |category| %>
      <% category.headers.uniq.each do |header| %>
          <h3 class="header-name"><%= header.name.upcase %></h3>
        <%category.products.each do |product| %>
            <% if product.premium %>
              <%= render 'shared/product-card', product: product %>
            <%end %>
        <% end %>
      <% end %>
    <% end %>

  </div>
  <div class="side"></div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="nav">
 <div class= "nav-list">
  <%= link_to root_path do %>
  <h4 class="nav-list-home">HOME</h4>
  <% end %>

  <% super_categories.each do |super_category| %>
    <div class="nav-dropdown">
      <div class="nav-dropdown-top">
        <h4 class= "nav-list-item nav-dropdown-top-item"> <%=super_category.name.upcase%></h4>
      </div>
      <div class="nav-dropdown-bottom">
          <% if super_category.name == 'Barthel Spezial' %>
            <h4><%= button_to "EMPFEHLUNGEN", recommended_path , method: :get, class: "nav-list-item nav-dropdown-bottom-item"%></h4>
          <% end %>
          <% super_category.categories.each do |category| %>
          <h4> <%= button_to "#{category.name.upcase}", products_path, method: :get, params: {products: {category: category.name}}, class: "nav-list-item nav-dropdown-bottom-item" %></h4>
        <% end %>
      </div>
    </div>
  <% end %>
  <h4 class="nav-list-item">WARENKORB</h4>
  <span class="nav-list-burger"><i id="burger-icon" class="fas fa-bars"></i></span>
 </div>
</div>

<div class="sidebar-box">
  <div class="sidebar-grey"></div>
  <div class="sidebar">
    <div class= "sidebar-list ">
     <h4 class="sidebar-list-home sidebar-list-item">HOME <i id="arrow-icon" class="fas fa-chevron-right"></i></h4>
     <% super_categories.each do |super_category| %>
       <h4> <%= button_to "#{super_category.name.upcase}", products_path, method: :get, params: {products: {super_category: super_category.name}}, class: "sidebar-list-item" %></h4>
     <% end %>
     <h4 class="sidebar-list-item">WARENKORB</h4>
    </div>
    <div class="sidebar-footer">
     <div class="sidebar-footer-top">
       <h3>Heimhauserstr. 6 | Müncher Freiheit</h3>
       <h3>ÖFFNUNGSZEITEN | Mo-Do 13.30-19 Uhr | Fr 12-13 Uhr & 14.30-19 Uhr | Sa 10.30 -12.30 Uhr</h3>
     </div>
     <div class="sidebar-footer-bottom">
       <h3>KONTAKT</h3>
       <h3>IMPRESSUM</h3>
       <h3>SERVICE & KONDITIONEN</h3>
     </div>
    </div>
  </div>

</div>

app/views/shared/_product-card.html.erb
<div class="card-product">
  <% if product.photo.attached?  %>
    <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
  <% else %>
    <%= image_tag 'barthel.png' %>
  <% end %>
  <div class="card-product-infos">
    <div class="card-product-infos-top">
      <h3><%= product.name %></h3>
      <p><%= product.year %></p>
    </div>
    <div class="card-product-infos-middle">
      <p><%= product.description %></p>
    </div>
    <div class="card-product-infos-bottom">
      <p><%= product.volume %></p>
      <div class="card-product-infos-bottom-right">
        <p> <strong><%= humanized_money_with_symbol(product.price)%></strong></p>
        <div class="popup-toggle">
          <div class="shopping-icon">
             <%= link_to line_items_path(product_id: product.id),remote: true ,method: :post do %>
            <p><i class="fas fa-shopping-cart"></i></p>
            <% end %>
          </div>
          <div class= "popup">
            <%= render 'shared/product_card_popup', product: product %>
          </div>
        </div>

      </div>

    </div>
  </div>
  <div class="card-product-special">
    <% if product.fresh %>
      <div class="card-product-special-fresh">
         <p><strong>NEU</strong></p>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_product_card_popup.html.erb
<div class="popup-close">
  <h4><i class="fas fa-times"></i></h4>
</div>


<%product.line_items.each do |item|%>
 <% if @line_items.include?(item) %>
    <p>Anzahl im Warenkorb</p>
    <div class= 'popup-rating'>
      <h3 class= 'minus'><%= link_to  line_item_reduce_path(id: item.id), remote: true,method: :post do %>
         <i class="fas fa-minus"></i>
        <% end %></h3>
      <h2 class= 'number'><%= item.quantity %></h2>
      <h3 class= 'plus'><%= link_to line_item_add_path(id: item.id),  remote: true ,method: :post do %>
        <i class="fas fa-plus"></i>
        <% end %></h3>
    </div>
  <% end %>
<% end %>

 <h4> <%= link_to "ZUM WARENKORB", cart_path(@current_cart) %></h4>